[project]
name = "learn-orjson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dacite>=1.8.1",
    "numpy>=2.1.3",
    "orjson>=3.10.11",
]
